build {
	core lib/ld init timer
	driver/platform/a64
	driver/sd_card/a64
	app/block_tester
}

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start platform | caps: 150 | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config
    + device sd_card | type: allwinner,sun50i-a64-mmc
      + io_mem | address: 0x01c0f000 | size: 0x1000
      + irq    | number: 92
      + clock bus-mmc0 | driver_name: ahb
      + clock mmc0     | driver_name: mmc
      + reset-domain mmc0
    + device emmc | type: allwinner,sun50i-a64-emmc
      + io_mem | address: 0x01c11000 | size: 0x1000
      + irq    | number: 94
      + clock bus-mmc2 | driver_name: ahb
      + clock mmc2     | driver_name: mmc
      + reset-domain mmc2
    + policy | label_prefix: a64_sd_card -> | info: yes
      + device sd_card
      + device emmc

+ start a64_sd_card | caps: 500 | ram: 16M
  + provides | + service Block
  + config | + default-policy | device: mmcblk0 | writeable: yes
  + route
    + service ROM | label: dtb | + parent | label: sd_card-} [board] {.dtb
    + service ROM              | + parent
    + service CPU              | + parent
    + service PD               | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Platform         | + child platform

+ start block_tester | ram: 64M
  + route
    + service ROM | + parent
    + service PD  | + parent
    + service RM  | + parent
    + service CPU | + parent
    + service LOG | + parent
    + any-service | + any-child
  + config | verbose: no | report: no | log: yes | stop_on_error: no
    + tests
      + sequential | length: 256M | size: 1M | io_buffer: 8M | batch: 4
      + sequential | length: 256M | size: 1M | io_buffer: 8M | batch: 4
                   | start: 2097152 | write: no
-
}

build_boot_image [build_artifacts]

run_genode_until {.*child "block_tester" exited with exit value 0.*} 60
