build {
	core lib/ld init timer
	driver/platform/a64
	driver/usb_host/a64
	driver/usb_block
	server/report_rom
	app/block_tester
}

create_boot_directory

install_config {
config | verbose: yes
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start report_rom
  + provides
    + service Report
    + service ROM
  + route | + any-service | + parent
  + config | verbose: yes
    + default-policy | report: usb -> usb -> devices

+ start platform | caps: 150 | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + route
    + service Timer | + child timer
    + any-service   | + parent
  + config | devices_rom: config
    + device usb_phy
      + io_mem | address: 0x01c19400 | size: 0x14
      + io_mem | address: 0x01c1a800 | size: 0x4
      + io_mem | address: 0x01c1b800 | size: 0x4
      + clock        usb-phy1
      + reset-domain usb-phy1
    + device ehci1
      + io_mem | address: 0x01c1b000 | size: 0x100
      + irq    | number: 106
      + clock        bus-ohci1
      + clock        bus-ehci1
      + clock        ohci1
      + reset-domain ehci1
      + reset-domain ohci1
    + policy | label: usb_host -> | info: yes
      + device ehci1
      + device usb_phy

+ start usb_host | caps: 200 | ram: 16M
  + binary a64_usb_host
  + provides | + service Usb
  + config
    + report | devices: yes
    + default-policy | class: 0x8
  + route
    + service Timer            | + child timer
    + service Report           | + child report_rom
    + service Platform         | + child platform
    + service ROM | label: dtb | + parent | label: usb-} [board] {.dtb
    + any-service              | + parent

+ start usb_block | ram: 4M
  + provides | + service Block
  + config | report: yes | writeable: no | label: usb-1-2
    .
    . Note, the label is probably only valid when a USB storage device
    . is plugged in directly to the second port of the LTS board.
    .
  + route
    + service Usb    | + child usb_host
    + service Report | + child report_rom
    + any-service
      + parent
      + any-child

+ start block_tester | ram: 64M
  + route
    + service ROM | + parent
    + service PD  | + parent
    + service RM  | + parent
    + service CPU | + parent
    + service LOG | + parent
    + any-service | + any-child
  + config | verbose: no | report: no | log: yes | stop_on_error: no
    + tests
      + sequential | length: 256M | write: no | size: 1M | io_buffer: 8M | batch: 4
-
}

build_boot_image [build_artifacts]

run_genode_until {.*child "block_tester" exited with exit value 0.*} 60
