build { core lib/ld init timer driver/platform driver/nic/emac server/nic_router }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start platform | caps: 150 | managing_system: yes
  + provides | + service Platform
  + route | + any-service | + parent
  + config | devices_rom: config
    + device syscon | type: allwinner,sun50i-a64-system-control
      + io_mem | address: 0x1c00000 | size: 0x1000
    + device emac   | type: allwinner,sun50i-a64-emac
      + io_mem | address: 0x1c30000 | size: 0x10000
      + irq | number: 114
    + policy | label: emac_nic ->  | info: yes
      + device syscon
      + device emac

+ start emac_nic | caps: 2000 | ram: 10M
  + config
  + route
    + service ROM | label: dtb | + parent | label: emac-pine_a64lts.dtb
    + service ROM              | + parent
    + service CPU              | + parent
    + service PD               | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Uplink           | + child nic_router
    + service Platform         | + child platform

+ start nic_router | caps: 200 | ram: 10M
  + provides
    + service Nic
    + service Uplink
  + route
    + service Timer | + child timer
    + any-service   | + parent
  + config | verbose_domain_state: yes | dhcp_discover_timeout_sec: 1
    + policy | label_prefix: emac_nic | domain: uplink
    + domain uplink
-
}

build_boot_image [build_artifacts]

run_genode_until forever
