build { core init timer driver/platform/a64 test/scp }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start a64_platform | caps: 150 | managing_system: yes
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config

+ start test-scp
  + config | program: 11 12 + . cr words cr
  + route
    + service Scp | + child a64_platform
    + any-service | + parent

+ start test-scp-2
  + binary test-scp
  + config | program: 1 2 3 4 5 6 .s cr
  + route
    + service Scp | + child a64_platform
    + any-service | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
