source ${genode_dir}/repos/dde_linux/run/wifi_config.inc


create_boot_directory
import_from_depot [depot_user]/pkg/a64_wifi

build {
	core lib/ld init timer
	driver/platform/a64
	driver/pin/a64
	driver/rtc/dummy
	server/dynamic_rom
	server/nic_router
	server/report_rom
	lib/vfs_jitterentropy
	lib/vfs_lwip test/lwip/http_srv
	driver/wifi
	lib/a64_wifi
}

proc quoted_wifi_config { args } {
	set xml [wifi_config {*}$args]
	set hid [exec [genode_dir]/tool/hid --import-xml format - << $xml]
	set result ""
	foreach line [split $hid "\n"] {
		if {$line == "wifi_config"} {
			append result "+ wifi_config"
		} elseif {$line != "-"} {
			append result "\n  |       $line"
		}
	}
	return $result
}

install_config {
config | prio_levels: 2
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start platform | caps: 150 | ram: 2M | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config
    + device pio | type: allwinner,sun50i-a64-pinctrl
      + io_mem | address: 0x1c20800 | size: 0x400 | . Ports A-H
      + io_mem | address: 0x1f02c00 | size: 0x400 | . Port L
      + irq    | number: 43                       | . Port B
      + irq    | number: 49                       | . Port G
      + irq    | number: 53                       | . Port H
      + irq    | number: 77                       | . Port L
    + device mmc1 | type: allwinner,sun50i-a64-mmc
      + io_mem | address: 0x01c10000 | size:    0x1000
      + irq    | number: 93
      + clock bus-mmc1 | driver_name: ahb
      + clock mmc1     | driver_name: mmc
      + reset-domain mmc1
      + power-domain pmic-wifi
    + device wifi_pwrseq | type: mmc-pwrseq-simple
      + clock dummy | driver_name: ext_clock
    + policy | label: a64_pio ->
      + device pio
    + policy | label: wifi -> | info: yes
      + device wifi_pwrseq
      + device mmc1

+ start a64_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform
  + config
    + select sdc1_clk | bank: G | index: 0 | function: 2
    + select sdc1_cmd | bank: G | index: 1 | function: 2
    + select sdc1_d0  | bank: G | index: 2 | function: 2
    + select sdc1_d1  | bank: G | index: 3 | function: 2
    + select sdc1_d2  | bank: G | index: 4 | function: 2
    + select sdc1_d3  | bank: G | index: 5 | function: 2
    + out wifi_pwrseq | bank: L | index: 2
    + policy | label: a64_wifi -> PL2 | pin: wifi_pwrseq

+ start test-lwip_httpsrv | ram: 128M
  + config
  | + libc | stdout: /dev/null | stderr: /dev/log | socket: /socket
  | + vfs
  |   + dir socket | + lwip | dhcp: yes
  |   + dir dev
  |     + log
  |     + null
  + route
    + service Nic | + child nic_router
    + any-service
      + parent
      + any-child

+ start nic_router | caps: 150 | ram: 8M
  + provides
    + service Nic
    + service Uplink
  + config | verbose: no | verbose_domain_state: yes | dhcp_discover_timeout_sec: 10
  |                                                  | dhcp_request_timeout_sec:  6
  | + policy | label_prefix: test-lwip_httpsrv | domain: downlink
  | + policy | label_prefix: wifi              | domain: uplink
  | + domain uplink
  |   |      verbose_packets:     no
  |   |      verbose_packet_drop: no
  |   |      icmp_echo_server:    yes
  |   + nat | domain: downlink | tcp-ports: 16384
  |   + tcp-forward | port: 443 | domain: downlink | to: 10.0.3.2
  |   + tcp-forward | port:  80 | domain: downlink | to: 10.0.3.2
  | + domain downlink
  |   |      verbose_packets:     no
  |   |      verbose_packet_drop: no
  |   |      interface:           10.0.3.1/24
  |   + dhcp-server | ip_first: 10.0.3.2 | ip_last: 10.0.3.2
  + route
    + service ROM   | + parent
    + service CPU   | + parent
    + service PD    | + parent
    + service LOG   | + parent
    + service Timer | + child timer

+ start dummy_rtc
  + provides | + service Rtc
  + config | year: 2023 | month: 02 | day: 27 | hour: 12 | minute: 0 | second: 0
  + route | + any-service | + parent

+ start state_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start accesspoints_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: no
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start devices_report_rom | ram: 2M
  + binary report_rom
  + provides
    + service Report
    + service ROM
  + config | verbose: yes
  + route
    + service ROM | + parent
    + service CPU | + parent
    + service PD  | + parent
    + service LOG | + parent
    + service Rtc | + any-child

+ start config_rom | ram: 4M
  + binary dynamic_rom
  + provides | + service ROM
  + config | verbose: yes
  | + rom wifi_config
  |   + inline | description: disconnect
  |     } [quoted_wifi_config 5 10 no {}] {
  |
  |   + sleep  | milliseconds: 15000
  |   + inline | description: connect
  |     } [quoted_wifi_config 5 10 no [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
  |
  |   + sleep  | milliseconds: 60000
  |   + inline | description: rfkill block
  |     } [quoted_wifi_config 5 10 yes [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
  |
  |   + sleep  | milliseconds: 30000
  |   + inline | description: rfkill unblock
  |     } [quoted_wifi_config 5 10 no [list "[wifi_ssid] [wifi_wpa] [wifi_psk] no"]] {
  |
  |   + sleep  | milliseconds: 30000
  + route
    + service ROM   | + parent
    + service CPU   | + parent
    + service PD    | + parent
    + service LOG   | + parent
    + service Rtc   | + any-child
    + service Timer | + child timer

+ start wifi | caps: 250 | ram: 32M | priority: -1
  + config | ld_verbose: yes
  | + report | mac_address: true
  | + libc | stdout: /dev/log | stderr: /dev/log | rtc: /dev/rtc | rng: /dev/urandom
  | + vfs
  |   + dir dev
  |     + log
  |     + null
  |     + rtc
  |     + jitterentropy random
  |     + jitterentropy urandom
  |   + dir firmware
  |     + tar wifi_firmware.tar
  + route
    + service Uplink                         | + child nic_router
    + service ROM | label: wifi.lib.so       | + parent | label: a64_wifi.lib.so
    + service ROM | label: wifi_firmware.tar | + parent | label: a64_wifi_firmware.tar
    + service ROM | label: dtb               | + parent | label: wifi-} [board] {.dtb
    + service ROM | label: wifi_config       | + child config_rom
    + service Report | label: accesspoints   | + child accesspoints_report_rom
    + service Report | label: state          | + child state_report_rom
    + service Report | label: devices        | + child devices_report_rom
    + service ROM                            | + parent
    + service CPU                            | + parent
    + service PD                             | + parent
    + service LOG                            | + parent
    + service Rtc                            | + any-child
    + service Timer                          | + child timer
    + service Platform                       | + child platform
-
}

build_boot_image [build_artifacts]

run_genode_until forever
