build { core lib/ld init timer driver/platform driver/pin/a64
        server/dynamic_rom app/pin_pulse app/pin_event }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start platform | caps: 150 | managing_system: yes
  + provides | + service Platform
  + route | + any-service | + parent
  + config | devices_rom: config
    + policy | label: a64_pio -> | + device pio
    + device pio
      + io_mem | address: 0x1c20800 | size: 0x400 | . Ports A-H
      + io_mem | address: 0x1f02c00 | size: 0x400 | . Port L
      + irq    | number: 43                       | . Port B
      + irq    | number: 49                       | . Port G
      + irq    | number: 53                       | . Port H
      + irq    | number: 77                       | . Port L

+ start dynamic_rom
  + provides | + service ROM
  + route
    + service Timer | + child timer
    + any-service | + parent
  + config | verbose: yes
    + rom config
      + inline | description: LED pulse
      | + config
      |   + out led    | bank: B | index: 2
      |   + in  button | bank: H | index: 8 | pull: up | irq: edges
      |   + policy | label_prefix: pin_event -> | pin: button
      |   + policy | label_prefix: pin_pulse -> | pin: led
      |
      + sleep  | milliseconds: 5000
      + inline | description: LED off
      | + config
      |   + out led    | bank: B | index: 2 | default: off
      |   + in  button | bank: H | index: 8 | pull: up | irq: edges
      |   + policy | label_prefix: pin_event -> | pin: button
      |
      + sleep  | milliseconds: 1000
      + inline | description: LED on
      | + config
      |   + out led    | bank: B | index: 2 | default: on
      |   + in  button | bank: H | index: 8 | pull: up | irq: edges
      |   + policy | label_prefix: pin_event -> | pin: button
      |
      + sleep  | milliseconds: 1000

+ start a64_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM | label: config | + child dynamic_rom
    + service ROM                 | + parent
    + service CPU                 | + parent
    + service PD                  | + parent
    + service LOG                 | + parent
    + service Platform            | + child platform

+ start pin_pulse
  + config | pulse_ms: 500 | pwm_period_ms: 50
  + route
    + service Timer       | + child timer
    + service Pin_control | + child a64_pio
    + service ROM         | + parent
    + service CPU         | + parent
    + service PD          | + parent
    + service LOG         | + parent

+ start pin_event
  + config
  + route
    + service Pin_state | + child a64_pio
    + service IRQ       | + child a64_pio
    + service ROM       | + parent
    + service CPU       | + parent
    + service PD        | + parent
    + service LOG       | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
