build { core lib/ld init timer test/at_protocol server/terminal_crosslink }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ default-route
  + any-service
    + parent
    + any-child

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start terminal_crosslink
  + provides | + service Terminal

+ start modem
  + binary test-at_protocol
  + config | role: modem

+ start driver
  + binary test-at_protocol
  + config | role: driver
-
}

build_boot_image [build_artifacts]

run_genode_until "modem.*Test done.*driver.*Test done.*\n" 30
