#
# Script to test audio driver on PinePhone
#

build {
	core lib/ld init timer lib/libc lib/libm lib/vfs lib/posix
	driver/platform/a64 driver/pin/a64
	driver/audio_control/pinephone
	driver/audio/a64
	server/report_rom
	server/record_play_mixer
	app/waveform_player
}

create_boot_directory

install_config {
config | verbose: yes | prio_levels: 2
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service RM
  + service ROM
  + service IO_MEM
  + service IRQ
  + service TRACE

+ default | caps: 100 | ram: 1M

+ default-route
  + any-service
    + parent
    + any-child

+ start timer | priority: 0
  + route | + any-service | + parent
  + provides | + service Timer

+ start report_rom | priority: -1
  + provides
    + service Report
    + service ROM
  + config | verbose: yes

+ start platform | caps: 200 | ram: 2M | managing_system: yes | priority: -1
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices: yes
    + policy | label: a64_pio ->
      + device pio
    + policy | label: audio_control ->
      + device audio_codec
      + device audio_analog
      + device audio_codec_soc
    + policy | label: audio -> | info: yes
      + device audio_interface
      + device dma_controller

+ start a64_pio | priority: -1
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform
  + config
    + out speaker-amp | bank: C | index: 7 | default: on | . speaker

+ start audio_control | priority: -1
  + binary pinephone_audio_control
  + config
    + mic      | volume: 60
    + earpiece | volume: 100
    + speaker  | volume: 20
    + codec    | target: soc
  + route
    + service Platform | + child platform
    + any-service      | + parent

+ start mixer | ram: 2M | priority: 0
  + binary record_play_mixer
  + provides
    + service Record
    + service Play
  + config | jitter_ms: 10
    + mix left      | + play | label: waveform_player -> left
    + mix right     | + play | label: waveform_player -> right
    + mix mic_left  | x play | label: audio -> mic_left
    + mix mic_right | x play | label: audio -> mic_right
    + policy | label: audio -> left  | record: left  | volume: 0.6
    + policy | label: audio -> right | record: right | volume: 0.0

+ start waveform_player | priority: 0
  + config | period_ms: 11
    + play | label: left  | wave: sine   | hz: 1000 | sample_rate_hz: 44100
    + play | label: right | wave: square | hz: 1000 | sample_rate_hz: 44100
  + route
    + any-service
      + parent
      + any-child

+ start audio | priority: 0
  + binary a64_audio
  + config | record_play: yes
  + route
    + service Platform | + child platform
    + service Record   | + child mixer
    + service Play     | + child mixer
    + any-service      | + parent
-
}

file copy [select_from_repositories board/[board]/devices] [run_dir]/genode/devices

build_boot_image [build_artifacts]

run_genode_until forever
