build { core init lib/ld server/event_dump driver/platform/a64 driver/button/pinephone }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start event_dump
  + provides | + service Event
  + route | + any-service | + parent
  + config

+ start a64_platform | caps: 150 | managing_system: yes
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config
    + device keyadc
      + io_mem | address: 0x1c21800 | size: 0x400
      + irq | number: 62
    + policy | label_prefix: pinephone_button ->
      + device keyadc

+ start pinephone_button
  + config
  + route
    + service Platform | + child a64_platform
    + service Event    | + child event_dump
    + any-service      | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
