assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/nitpicker

build {
	driver/platform/a64
	driver/camera/pinephone
	driver/framebuffer/de
	driver/pin/a64
	test/framebuffer
	app/dummy
}

install_config {
config | verbose: yes
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start platform | caps: 200 | ram: 2M | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + config | devices_rom: config
  | + device pio | type: allwinner,sun50i-a64-pinctrl
  |   + io_mem | address: 0x1c20800 | size: 0x400 | . Ports A-H
  |   + io_mem | address: 0x1f02c00 | size: 0x400 | . Port L
  |   + irq    | number: 43                       | . Port B
  |   + irq    | number: 49                       | . Port G
  |   + irq    | number: 53                       | . Port H
  |   + irq    | number: 77                       | . Port L
  |
  | + device dphy | type: allwinner,sun50i-a64-mipi-dphy
  |   + io_mem | address: 0x01ca1000 | size: 0x1000
  |   + clock bus-mipi-dsi | driver_name: bus
  |   + clock dsi-dphy | driver_name: mod
  |   + reset-domain mipi-dsi
  |
  | + device dsi | type: allwinner,sun50i-a64-mipi-dsi
  |   + io_mem | address: 0x01ca0000 | size: 0x1000
  |   + reset-domain mipi-dsi
  |   + clock bus-mipi-dsi
  |   + clock pll-mipi
  |
  | + device syscon | type: allwinner,sun50i-a64-system-control
  |   + io_mem | address: 0x01c00000 | size: 0x1000
  |
  | + device de2_bus | type: allwinner,sun50i-a64-de2
  |   + io_mem | address:  0x1000000 | size: 0x400000
  |   + reset-domain de
  |   + clock bus-de  | driver_name: bus
  |   + clock de-sclk | driver_name: mod
  |   + clock dummy   | driver_name: bus-mixer0
  |   + clock dummy   | driver_name: mixer0
  |   + clock dummy   | driver_name: bus-mixer1
  |   + clock dummy   | driver_name: mixer1
  |   + clock pll-de
  |   + clock pll-video0
  |
  | + device r_pwm | type: allwinner,sun50i-a64-pwm
  |   + io_mem | address: 0x01f03800 | size: 0x400
  |   + clock osc24M | driver_name: mod
  |   + clock osc24M | driver_name: bus
  |
  | + device tcon0 | type: allwinner,sun8i-a83t-tcon-lcd
  |   + io_mem | address: 0x01c0c000 | size: 0x1000
  |   + irq    | number: 118
  |   + reset-domain tcon0
  |   + reset-domain lvds
  |   + power-domain pmic-gpio0
  |   + clock bus-tcon0 | driver_name: ahb
  |   + clock tcon0     | driver_name: tcon-ch0
  |   + clock dummy     | driver_name: tcon-data-clock
  |
  | + device tcon1 | type: allwinner,sun8i-a83t-tcon-tv
  |   + io_mem | address: 0x01c0d000 | size: 0x1000
  |   + irq    | number: 119
  |   + reset-domain tcon1
  |   + clock bus-tcon1 | driver_name: ahb
  |   + clock tcon1     | driver_name: tcon-ch1
  |
  | + policy | label_prefix: a64_pio ->
  |   + device pio
  |
  | + policy | label_prefix: fb ->  | info: yes
  |   + device dphy
  |   + device dsi
  |   + device syscon
  |   + device de2_bus
  |   + device r_pwm
  |   + device tcon0
  |   + device tcon1
  |
  | + device csi | type: allwinner,sun50i-a64-csi
  |   + io_mem | address: 0x01cb0000 | size: 0x1000
  |   + irq    | number: 116
  |   + reset-domain csi
  |   x power-domain pmic-aldo1
  |   + power-domain pmic-csi
  |   + clock bus-csi  | driver_name: bus
  |   + clock csi-sclk | driver_name: mod
  |   + clock dram-csi | driver_name: ram
  |   + clock csi-mclk | driver_name: xclk
  |
  | + policy | label_prefix: camera ->  | info: yes
  |   + device csi
  + route
    + any-service
      + parent
      + any-child

+ start a64_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform
  + config
    + select lcd-pwm          | bank: L | index: 10 | function: 2
    + out    backlight        | bank: H | index: 10
    + out    lcd-reset        | bank: D | index: 23 | default:  0
    + select csi-pclk         | bank: E | index:  0 | function: 2
    + select csi-mclk         | bank: E | index:  1 | function: 2
    + select csi-hsync        | bank: E | index:  2 | function: 2
    + select csi-vsync        | bank: E | index:  3 | function: 2
    + select csi-d0           | bank: E | index:  4 | function: 2
    + select csi-d1           | bank: E | index:  5 | function: 2
    + select csi-d2           | bank: E | index:  6 | function: 2
    + select csi-d3           | bank: E | index:  7 | function: 2
    + select csi-d4           | bank: E | index:  8 | function: 2
    + select csi-d5           | bank: E | index:  9 | function: 2
    + select csi-d6           | bank: E | index: 10 | function: 2
    + select csi-d7           | bank: E | index: 11 | function: 2
    + out    csi-sck          | bank: E | index: 12
    + in     csi-sck          | bank: E | index: 12
    + out    csi-sda          | bank: E | index: 13
    + in     csi-sda          | bank: E | index: 13
    + out    gc2145-reset     | bank: E | index: 16
    + out    gc2145-powerdown | bank: E | index: 17
    + out    ov5460-powerdown | bank: C | index:  0
    + out    ov5460-reset     | bank: D | index:  3
    + in     ov5460-reset     | bank: D | index:  3
    + policy | label: fb -> PH10     | pin: backlight
    + policy | label: fb -> PD23     | pin: lcd-reset
    + policy | label: camera -> PC0  | pin: ov5460-powerdown
    + policy | label: camera -> PD3  | pin: ov5460-reset
    + policy | label: camera -> PE12 | pin: csi-sck
    + policy | label: camera -> PE13 | pin: csi-sda
    + policy | label: camera -> PE16 | pin: gc2145-reset
    + policy | label: camera -> PE17 | pin: gc2145-powerdown
+ start nitpicker
  + provides
    + service Gui
    + service Capture
    + service Event
  + config | verbose: yes
    + capture
    + event
    + domain default | layer: 1 | content: client | label: no
    + default-policy | domain: default

+ start fb | caps: 250 | ram: 40M
  + binary de_fb
  + route
    + service ROM | label: dtb               | + parent | label: de-pinephone.dtb
    + service Platform                       | + child platform
    + service Pin_control | label_last: PH10 | + child a64_pio | label: fb -> PH10
    + service Pin_control | label_last: PD23 | + child a64_pio | label: fb -> PD23
    + service Timer                          | + child timer
    + service Capture                        | + child nitpicker
    + any-service                            | + parent

+ start dummy-log
  + binary dummy
  + provides | + service LOG
  + config | + log_service
  + route | + any-service | + parent

+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom config
      + inline | description: camera front present 640x480@15
      | + config
      |   + parent-provides
      |     + service ROM
      |     + service PD
      |     + service CPU
      |     + service LOG
      |     + service Platform
      |     + service Timer
      |     + service Capture
      |     + service Pin_control
      |     + service Pin_state
      |     + service Gui
      |   + start camera | caps: 250 | ram: 80M
      |     + binary pinephone_camera
      |     + config | width: 640 | height: 480 | fps: 15 | format: yuv | camera: front
      |     + route
      |       + service ROM | label: dtb | + parent | label: camera.dtb
      |       + any-service              | + parent
      |
      + sleep | milliseconds: 10000
      + inline | description: camera back present 640x480@15
      | + config
      |   + parent-provides
      |     + service ROM
      |     + service PD
      |     + service CPU
      |     + service LOG
      |     + service Platform
      |     + service Timer
      |     + service Capture
      |     + service Pin_control
      |     + service Pin_state
      |     + service Gui
      |   + start camera | version: 2 | caps: 250 | ram: 80M
      |     + binary pinephone_camera
      |     + config | width: 640 | height: 480 | fps: 15 | format: yuv | camera: rear
      |     + route
      |       + service ROM | label: dtb | + parent | label: camera.dtb
      |       + any-service              | + parent
      |
      + sleep | milliseconds: 10000

+ start dynamic_init | caps: 1000 | ram: 128M
  + binary init
  + route
    + service ROM | label: config                | + child dynamic_rom
    + service ROM | label_last: camera.dtb       | + parent | label: camera-pinephone.dtb
    + service Platform | label_suffix: camera -> | + child platform | label: camera -> 
    + service Pin_control | label_last: PC0      | + child a64_pio | label: camera -> PC0
    + service Pin_control | label_last: PD3      | + child a64_pio | label: camera -> PD3
    + service Pin_control | label_last: PE12     | + child a64_pio | label: camera -> PE12
    + service Pin_control | label_last: PE13     | + child a64_pio | label: camera -> PE13
    + service Pin_control | label_last: PE16     | + child a64_pio | label: camera -> PE16
    + service Pin_control | label_last: PE17     | + child a64_pio | label: camera -> PE17
    + service Pin_state   | label_last: PC0      | + child a64_pio | label: camera -> PC0
    + service Pin_state   | label_last: PD3      | + child a64_pio | label: camera -> PD3
    + service Pin_state   | label_last: PE12     | + child a64_pio | label: camera -> PE12
    + service Pin_state   | label_last: PE13     | + child a64_pio | label: camera -> PE13
    + service Pin_state   | label_last: PE16     | + child a64_pio | label: camera -> PE16
    + service Pin_state   | label_last: PE17     | + child a64_pio | label: camera -> PE17
    + service Timer                              | + child timer
    + service Gui                                | + child nitpicker
    + any-service                                | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
