assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/dynamic_rom

build {
	driver/platform/a64
	driver/framebuffer/de
	driver/pin/a64
	test/framebuffer
}

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start platform | caps: 200 | ram: 2M | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + config | devices_rom: config
  | + device pio | type: allwinner,sun50i-a64-pinctrl
  |   + io_mem | address: 0x1c20800 | size: 0x400 | . Ports A-H
  |   + io_mem | address: 0x1f02c00 | size: 0x400 | . Port L
  |   + irq    | number: 43                       | . Port B
  |   + irq    | number: 49                       | . Port G
  |   + irq    | number: 53                       | . Port H
  |   + irq    | number: 77                       | . Port L
  |
  | + device dphy | type: allwinner,sun50i-a64-mipi-dphy
  |   + io_mem | address: 0x01ca1000 | size: 0x1000
  |   + clock bus-mipi-dsi | driver_name: bus
  |   + clock dsi-dphy     | driver_name: mod
  |   + reset-domain mipi-dsi
  |
  | + device dsi | type: allwinner,sun50i-a64-mipi-dsi
  |   + io_mem | address: 0x01ca0000 | size: 0x1000
  |   + reset-domain mipi-dsi
  |   + clock bus-mipi-dsi
  |   + clock pll-mipi
  |
  | + device syscon | type: allwinner,sun50i-a64-system-control
  |   + io_mem | address: 0x01c00000 | size: 0x1000
  |
  | + device de2_bus | type: allwinner,sun50i-a64-de2
  |   + io_mem | address: 0x1000000 | size: 0x400000
  |   + reset-domain de
  |   + clock bus-de  | driver_name: bus
  |   + clock de-sclk | driver_name: mod
  |   + clock dummy   | driver_name: bus-mixer0
  |   + clock dummy   | driver_name: mixer0
  |   + clock dummy   | driver_name: bus-mixer1
  |   + clock dummy   | driver_name: mixer1
  |   + clock pll-de
  |   + clock pll-video0
  |
  | + device r_pwm | type: allwinner,sun50i-a64-pwm
  |   + io_mem | address: 0x01f03800 | size: 0x400
  |   + clock osc24M | driver_name: mod
  |   + clock osc24M | driver_name: bus
  |
  | + device tcon0 | type: allwinner,sun8i-a83t-tcon-lcd
  |   + io_mem | address: 0x01c0c000 | size: 0x1000
  |   + irq    | number: 118
  |   + reset-domain tcon0
  |   + reset-domain lvds
  |   + power-domain pmic-gpio0
  |   + clock bus-tcon0 | driver_name: ahb
  |   + clock tcon0     | driver_name: tcon-ch0
  |   + clock dummy     | driver_name: tcon-data-clock
  |
  | + device tcon1 | type: allwinner,sun8i-a83t-tcon-tv
  |   + io_mem | address: 0x01c0d000 | size: 0x1000
  |   + irq    | number: 119
  |   + reset-domain tcon1
  |   + clock bus-tcon1 | driver_name: ahb
  |   + clock tcon1     | driver_name: tcon-ch1
  |
  | + policy | label: a64_pio ->
  |   + device pio
  |
  | + policy | label: fb -> | info: yes
  |   + device dphy
  |   + device dsi
  |   + device syscon
  |   + device de2_bus
  |   + device r_pwm
  |   + device tcon0
  |   + device tcon1
  |
  + route | + any-service | + parent

+ start a64_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform
  + config
    + select lcd-pwm   | bank: L | index: 10 | function: 2
    + out    backlight | bank: H | index: 10 | default:  0
    + out    lcd-reset | bank: D | index: 23 | default:  0
    + policy | label: fb -> PH10 | pin: backlight
    + policy | label: fb -> PD23 | pin: lcd-reset

+ start dynamic_rom | ram: 4M
  + provides | + service ROM
  + config | verbose: yes
    + rom config
      + inline | description: fb present
      | + config
      |   + parent-provides
      |     + service ROM
      |     + service PD
      |     + service CPU
      |     + service LOG
      |     + service Platform
      |     + service Timer
      |     + service Capture
      |     + service Pin_control
      |   + start fb | caps: 250 | ram: 40M
      |     + binary de_fb
      |     + route | + any-service | + parent
      |
      + sleep | milliseconds: 10000
      + inline | description: fb absent
      | + config
      |   + parent-provides
      |     + service ROM
      |     + service PD
      |     + service CPU
      |     + service LOG
      |     + service Platform
      |     + service Timer
      |     + service Capture
      |     + service Pin_control
      |
      + sleep | milliseconds: 10000

+ start dynamic_init | caps: 300 | ram: 45M
  + binary init
  + route
    + service ROM | label: config            | + child dynamic_rom
    + service ROM | label_last: dtb          | + parent | label: de-pinephone.dtb
    + service Platform                       | + child platform | label: fb -> 
    + service Pin_control | label_last: PH10 | + child a64_pio | label: fb -> PH10
    + service Pin_control | label_last: PD23 | + child a64_pio | label: fb -> PD23
    + service Timer                          | + child timer
    + service Capture                        | + child test-framebuffer
    + any-service                            | + parent

+ start test-framebuffer | ram: 10M
  + provides | + service Capture
  + config
-
}

build_boot_image [build_artifacts]

run_genode_until forever
