assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/raw/pinephone-devices

build {
	driver/platform/a64
	driver/framebuffer/de
	driver/pin/a64
	driver/touch/goodix
	server/event_dump
	server/event_filter
	test/framebuffer
}

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start drivers | caps: 1500 | ram: 64M | managing_system: yes
  + binary init
  + route
    + service ROM | label: config | + parent | label: drivers.config
    + service Timer               | + child timer
    + service Capture             | + child test-framebuffer
    + service Event               | + child event_dump
    + any-service                 | + parent

+ start test-framebuffer | ram: 10M
  + provides | + service Capture
  + config

+ start event_dump
  + provides | + service Event
  + config
-
}

foreach file [glob "[genode_dir]/repos/allwinner/recipes/raw/drivers_interactive-pinephone/*.config"] {
	copy_file $file [run_dir]/genode/ }

build_boot_image [build_artifacts]

run_genode_until forever
