build { core lib/ld init timer test/pin_control }

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start test-pin_control
  + route
    + service Timer | + child timer
    + any-service | + parent
-
}

build_boot_image [build_artifacts]

run_genode_until forever
