build {
	core init timer lib/ld
	server/report_rom server/event_dump
	driver/platform/a64 driver/power/pinephone
}

create_boot_directory

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM
  + service IO_MEM
  + service IRQ

+ default | caps: 100 | ram: 1M

+ start timer
  + route | + any-service | + parent
  + provides | + service Timer

+ start report_rom
  + route | + any-service | + parent
  + provides
    + service Report
    + service ROM
  + config | verbose: yes

+ start event_dump
  + provides | + service Event
  + config
  + route | + any-service | + parent

+ start a64_platform | caps: 150 | managing_system: yes
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config
    + device rintc
      + io_mem | address: 0x1f00c00 | size: 0x400
      + irq | number: 64
    + policy | label_prefix: pinephone_power ->
      + device rintc

+ start pinephone_power
  + route
    + service Timer               | + child timer
    + service Scp                 | + child a64_platform
    + service Platform            | + child a64_platform
    + service Report              | + child report_rom
    + service Event               | + child event_dump
    + service ROM | label: system | + parent | label: config
    + any-service                 | + parent
  + config | period_ms: 3000 | system_rom: config | state:
    .
    . supported 'state' attribute values are 'reset', 'poweroff'
    .
-
}

build_boot_image [build_artifacts]

run_genode_until forever
