assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init

build {
	driver/platform/a64
	driver/touch/goodix
	server/event_dump
	driver/pin/a64
}

install_config {
config
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start event_dump
  + provides | + service Event
  + config

+ start platform | caps: 150 | managing_system: yes
  + binary a64_platform
  + provides
    + service Platform
    + service Scp
  + route | + any-service | + parent
  + config | devices_rom: config
    + device pio
      + io_mem | address: 0x1c20800 | size: 0x400 | . Ports A-H
      + io_mem | address: 0x1f02c00 | size: 0x400 | . Port L
      + irq    | number: 43                       | . Port B
      + irq    | number: 49                       | . Port G
      + irq    | number: 53                       | . Port H
      + irq    | number: 77                       | . Port L
    + device i2c0 | type: allwinner,sun6i-a31-i2c
      + io_mem | address: 0x01c2ac00 | size:  0x400
      + irq    | number: 38
      + clock bus-i2s0 | driver_name:
      + clock bus-twi0 | driver_name:
      + reset-domain twi0
      + power-domain pmic-gpio0
    + policy | label: a64_pio ->
      + device pio
    + policy | label: goodix_touch -> | info: yes
      + device i2c0

+ start a64_pio
  + provides
    + service Pin_state
    + service Pin_control
    + service IRQ
  + route
    + service ROM      | + parent
    + service CPU      | + parent
    + service PD       | + parent
    + service LOG      | + parent
    + service Platform | + child platform
  + config
    + select touchscreen-i2c-sck | bank: H | index: 0 | function: 2
    + select touchscreen-i2c-sda | bank: H | index: 1 | function: 2
    + out    touchscreen-int     | bank: H | index: 4
    + in     touchscreen-int     | bank: H | index: 4 | irq: falling
    + out    touchscreen-reset   | bank: H | index: 11
    + policy | label: goodix_touch -> PH11 | pin: touchscreen-reset
    + policy | label: goodix_touch -> PH4  | pin: touchscreen-int

+ start goodix_touch | caps: 250 | ram: 40M
  + route
    + service ROM | label: dtb | + parent | label: goodix-pinephone.dtb
    + service RM               | + parent
    + service ROM              | + parent
    + service PD               | + parent
    + service CPU              | + parent
    + service LOG              | + parent
    + service Timer            | + child timer
    + service Platform         | + child platform
    + service Event            | + child event_dump
    + service Pin_control      | + child a64_pio
    + service IRQ              | + child a64_pio | label: goodix_touch -> PH4
-
}

build_boot_image [build_artifacts]

run_genode_until forever
